import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design system palette — Synthesized Intelligence
        "inverse-primary": "#005ac2",
        "surface-container-lowest": "#010f1f",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "primary-container": "#4d8eff",
        "tertiary": "#4edea3",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#00285d",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary-container": "#d6e5ff",
        "secondary-fixed": "#d4e3ff",
        "on-primary": "#002e6a",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#273647",
        "on-secondary": "#00315d",
        "secondary-container": "#0267b8",
        "outline-variant": "#424754",
        "on-tertiary-container": "#00311f",
        "tertiary-container": "#00a572",
        "surface": "#051424",
        "on-tertiary": "#003824",
        "on-surface-variant": "#c2c6d6",
        "surface-container": "#122131",
        "on-primary-fixed-variant": "#004395",
        "surface-variant": "#273647",
        "surface-bright": "#2c3a4c",
        "on-error": "#690005",
        "surface-container-high": "#1c2b3c",
        "primary": "#adc6ff",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "surface-container-low": "#0d1c2d",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#001c39",
        "on-surface": "#d4e4fa",
        "surface-dim": "#051424",
        "inverse-surface": "#d4e4fa",
        "inverse-on-surface": "#233143",
        "background": "#051424",
        "secondary": "#a4c9ff",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#004883",
        "on-background": "#d4e4fa",
        "surface-tint": "#adc6ff",
        "outline": "#8c909f",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#6ffbbe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
      animation: {
        "pulse-ring": "pulse-ring 3s ease-in-out infinite",
        "ai-breathe": "ai-breathe 3s ease-in-out infinite",
        "scan": "scan 4s linear infinite",
        "waveform": "waveform 1.2s ease-in-out infinite",
      },
      keyframes: {
        "pulse-ring": {
          "0%, 100%": { transform: "scale(0.95)", opacity: "0.5" },
          "50%": { transform: "scale(1.05)", opacity: "0.8" },
        },
        "ai-breathe": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8" },
          "50%": { transform: "scale(1.05)", opacity: "1" },
        },
        "scan": {
          "0%": { top: "-100px" },
          "100%": { top: "100vh" },
        },
        "waveform": {
          "0%, 100%": { height: "4px" },
          "50%": { height: "24px" },
        },
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};

export default config;
